{
 "title": "Apache Kafka Overview Cluster Dashboard",
 "tags": [
  "kafka",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Kafka Brokers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  },
  {
   "title": "Total Cluster Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (topic) (kafka_topic_partitions))"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kafka_topic_partitions)" }
   ]
  },
  {
   "title": "Consumer Group Lag (Pending Messages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "messages" } },
   "targets": [
    {
     "expr": "sum by (consumergroup, topic) (kafka_consumergroup_lag) > 0",
     "legendFormat": "Group: {{consumergroup}} (Topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message Production Rate (Offset growth / sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_topic_partition_current_offset[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}